### ISSUE TITLE
v0.15.1 to latest

### ISSUE THREAD

**Issue by magick93** [Pakcoin-project/pakcoin#1]
Hello

I have a wallet.dat for v0.15.1.

What is the recommended process to migrate to the latest version? Is it the same chain? Has there been a swap?

Thanks

**Comment by drwatson84** [comment]
Hi,
There is no direct method, instead you need to contact our support at twitter.com/pakcoinofficial or facebook.com/pakcoinofficial and they would guide you about this..
Regards
