### ISSUE TITLE
Code need updating to Version: 1.65.1.0

### ISSUE THREAD

**Issue by lurchinms** [Pakcoin-project/pakcoin#2]
makefile.unix:179: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1

**Comment by drwatson84** [comment]
You need to use sudo before make

**Comment by lurchinms** [comment]
sudo make -f makefile.unix
OUTPUT
makefile.unix:179: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1
